//! LLM client trait and implementations.

use async_trait::async_trait;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::time::Duration;
use tracing::{debug, info, warn};

use super::config::LLMConfig;
use super::prompts;
use crate::errors::{Result, RiwaqError};
use crate::models::snapshot::CodebaseSnapshot;

/// Response from the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMResponse {
    /// Generated content.
    pub content: String,

    /// Number of prompt tokens used.
    pub prompt_tokens: Option<usize>,

    /// Number of completion tokens used.
    pub completion_tokens: Option<usize>,

    /// Model used.
    pub model: String,

    /// Whether the response was streamed.
    pub streamed: bool,

    /// Finish reason (stop, length, etc.).
    pub finish_reason: Option<String>,
}

/// Architecture overview generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArchitectureOverview {
    /// Markdown content.
    pub content: String,

    /// Detected architectural patterns.
    pub patterns: Vec<String>,

    /// Main components identified.
    pub components: Vec<ComponentSummary>,
}

/// Summary of a component.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComponentSummary {
    /// Component name.
    pub name: String,

    /// Description.
    pub description: String,

    /// Responsibilities.
    pub responsibilities: Vec<String>,

    /// Dependencies.
    pub dependencies: Vec<String>,
}

/// Architecture Decision Record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Adr {
    /// ADR number/ID.
    pub id: String,

    /// Title.
    pub title: String,

    /// Context (why this decision was needed).
    pub context: String,

    /// Decision made.
    pub decision: String,

    /// Alternatives considered.
    pub alternatives: Vec<String>,

    /// Consequences of the decision.
    pub consequences: Vec<String>,

    /// Status (proposed, accepted, deprecated, etc.).
    pub status: String,
}

/// Answer to a question with references.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnswerWithRefs {
    /// The answer text.
    pub answer: String,

    /// References to files.
    pub file_refs: Vec<FileReference>,

    /// Confidence score (0-1).
    pub confidence: f32,
}

/// Reference to a specific location in a file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileReference {
    /// File path.
    pub path: String,

    /// Line number (1-indexed).
    pub line: Option<usize>,

    /// Relevant snippet.
    pub snippet: Option<String>,

    /// Why this file is relevant.
    pub relevance: String,
}

/// Trait for LLM clients.
///
/// This trait abstracts the LLM provider, allowing easy swapping
/// between different providers (OpenRouter, Z.ai, local models, etc.).
#[async_trait]
pub trait LLMClient: Send + Sync {
    /// Generate an architecture overview for the codebase.
    async fn generate_architecture_overview(
        &self,
        snapshot: &CodebaseSnapshot,
    ) -> Result<ArchitectureOverview>;

    /// Generate documentation for individual components.
    async fn generate_component_docs(
        &self,
        snapshot: &CodebaseSnapshot,
    ) -> Result<Vec<ComponentSummary>>;

    /// Generate Architecture Decision Records.
    async fn generate_adrs(&self, snapshot: &CodebaseSnapshot) -> Result<Vec<Adr>>;

    /// Answer a question about the codebase.
    async fn answer_question(
        &self,
        snapshot: &CodebaseSnapshot,
        question: &str,
    ) -> Result<AnswerWithRefs>;

    /// Raw completion - send a prompt and get a response.
    async fn complete(&self, prompt: &str, system_prompt: Option<&str>) -> Result<LLMResponse>;

    /// Stream a completion (returns content incrementally).
    async fn complete_stream(
        &self,
        prompt: &str,
        system_prompt: Option<&str>,
        callback: Box<dyn Fn(String) + Send>,
    ) -> Result<LLMResponse>;
}

/// HTTP-based LLM client for OpenAI-compatible APIs.
pub struct HttpLlmClient {
    config: LLMConfig,
    client: Client,
}

impl HttpLlmClient {
    /// Create a new HTTP LLM client.
    pub fn new(config: LLMConfig) -> Result<Self> {
        let timeout = Duration::from_secs(config.timeout_secs);

        let client = Client::builder()
            .timeout(timeout)
            .build()
            .map_err(|e| RiwaqError::Internal(format!("Failed to create HTTP client: {}", e)))?;

        Ok(Self { config, client })
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Result<Self> {
        Self::new(LLMConfig::default())
    }

    /// Make a chat completion request.
    async fn chat_completion(&self, messages: Vec<ChatMessage>) -> Result<LLMResponse> {
        let api_key = self
            .config
            .api_key
            .as_ref()
            .ok_or_else(|| RiwaqError::MissingEnvVar("RIWAQ_LLM_API_KEY".to_string()))?;

        let endpoint = format!("{}/chat/completions", self.config.endpoint.trim_end_matches('/'));

        let request_body = ChatCompletionRequest {
            model: self.config.model.clone(),
            messages,
            max_tokens: self.config.max_tokens,
            temperature: self.config.temperature,
            stream: false,
        };

        debug!(endpoint = %endpoint, model = %self.config.model, "Sending LLM request");

        let mut retries = 0;
        loop {
            let response = self
                .client
                .post(&endpoint)
                .header("Authorization", format!("Bearer {}", api_key))
                .header("Content-Type", "application/json")
                .json(&request_body)
                .send()
                .await;

            match response {
                Ok(resp) => {
                    let status = resp.status();

                    if status.is_success() {
                        let api_response: ChatCompletionResponse = resp
                            .json()
                            .await
                            .map_err(|e| RiwaqError::llm_error(format!("Failed to parse response: {}", e)))?;

                        let choice = api_response
                            .choices
                            .first()
                            .ok_or_else(|| RiwaqError::llm_error("No choices in response"))?;

                        return Ok(LLMResponse {
                            content: choice.message.content.clone(),
                            prompt_tokens: api_response.usage.as_ref().map(|u| u.prompt_tokens),
                            completion_tokens: api_response.usage.as_ref().map(|u| u.completion_tokens),
                            model: api_response.model,
                            streamed: false,
                            finish_reason: choice.finish_reason.clone(),
                        });
                    } else if status.as_u16() == 429 {
                        // Rate limited
                        if retries < self.config.max_retries {
                            retries += 1;
                            let delay = 2u64.pow(retries);
                            warn!(retries, delay_secs = delay, "Rate limited, retrying");
                            tokio::time::sleep(Duration::from_secs(delay)).await;
                            continue;
                        }
                        return Err(RiwaqError::LlmRateLimited {
                            retry_after_secs: 60,
                        });
                    } else {
                        let error_text = resp.text().await.unwrap_or_default();
                        return Err(RiwaqError::llm_error(format!(
                            "API error ({}): {}",
                            status, error_text
                        )));
                    }
                }
                Err(e) => {
                    if retries < self.config.max_retries {
                        retries += 1;
                        warn!(error = %e, retries, "Request failed, retrying");
                        tokio::time::sleep(Duration::from_secs(1)).await;
                        continue;
                    }
                    return Err(RiwaqError::llm_error(format!("Request failed: {}", e)));
                }
            }
        }
    }

    /// Prepare snapshot context for the LLM.
    fn prepare_snapshot_context(&self, snapshot: &CodebaseSnapshot) -> String {
        let mut context = String::new();

        // Project metadata
        context.push_str(&format!(
            "# Project: {}\n\n",
            snapshot.metadata.project_name
        ));

        // Statistics
        context.push_str("## Statistics\n");
        context.push_str(&format!("- Files: {}\n", snapshot.statistics.total_files));
        context.push_str(&format!("- Modules: {}\n", snapshot.statistics.total_modules));
        context.push_str(&format!("- Functions: {}\n", snapshot.statistics.total_functions));
        context.push_str(&format!("- Types: {}\n", snapshot.statistics.total_types));
        context.push_str(&format!(
            "- Lines of Code: {}\n\n",
            snapshot.statistics.total_lines
        ));

        // Languages
        context.push_str("## Languages\n");
        for lang in &snapshot.statistics.languages {
            context.push_str(&format!("- {}: {} files, {} lines\n", lang.language, lang.file_count, lang.line_count));
        }
        context.push('\n');

        // Modules summary
        context.push_str("## Modules\n");
        for module in &snapshot.modules {
            context.push_str(&format!(
                "### {}\n- Path: {}\n- Files: {}\n- Public functions: {}\n\n",
                module.name,
                module.path,
                module.files.len(),
                module.public_functions.join(", ")
            ));
        }

        // Dependencies
        if !snapshot.dependency_graph.circular_deps.is_empty() {
            context.push_str("## Circular Dependencies (Issues)\n");
            for cycle in &snapshot.dependency_graph.circular_deps {
                context.push_str(&format!("- {}\n", cycle.join(" -> ")));
            }
            context.push('\n');
        }

        // Services
        if !snapshot.services.is_empty() {
            context.push_str("## Services/Entry Points\n");
            for service in &snapshot.services {
                context.push_str(&format!(
                    "- {} ({:?}): {:?}\n",
                    service.name, service.kind, service.entry_file
                ));
            }
            context.push('\n');
        }

        // Git insights
        if let Some(repo) = &snapshot.git_insights.repository {
            context.push_str("## Repository\n");
            context.push_str(&format!("- Name: {}\n", repo.name));
            context.push_str(&format!("- Total commits: {}\n", repo.total_commits));
            if let Some(url) = &repo.remote_url {
                context.push_str(&format!("- Remote: {}\n", url));
            }
            context.push('\n');
        }

        // Hotspots
        if !snapshot.git_insights.domains.is_empty() {
            context.push_str("## Detected Domains\n");
            for domain in &snapshot.git_insights.domains {
                context.push_str(&format!(
                    "- {}: {} files (activity: {:.1}%)\n",
                    domain.name,
                    domain.files.len(),
                    domain.activity_level * 100.0
                ));
            }
        }

        context
    }
}

#[async_trait]
impl LLMClient for HttpLlmClient {
    async fn generate_architecture_overview(
        &self,
        snapshot: &CodebaseSnapshot,
    ) -> Result<ArchitectureOverview> {
        let context = self.prepare_snapshot_context(snapshot);
        let prompt = prompts::architecture_overview_prompt(&context);

        info!("Generating architecture overview");

        let response = self
            .complete(&prompt, Some(prompts::SYSTEM_PROMPT))
            .await?;

        // Parse the markdown response
        Ok(ArchitectureOverview {
            content: response.content,
            patterns: Vec::new(),     // TODO: Extract from response
            components: Vec::new(),   // TODO: Extract from response
        })
    }

    async fn generate_component_docs(
        &self,
        snapshot: &CodebaseSnapshot,
    ) -> Result<Vec<ComponentSummary>> {
        let mut docs = Vec::new();

        for module in &snapshot.modules {
            let prompt = prompts::component_doc_prompt(&module.name, &module.path, &module.public_functions);

            let response = self
                .complete(&prompt, Some(prompts::SYSTEM_PROMPT))
                .await?;

            docs.push(ComponentSummary {
                name: module.name.clone(),
                description: response.content,
                responsibilities: Vec::new(),
                dependencies: module
                    .dependencies
                    .iter()
                    .map(|d| d.target.clone())
                    .collect(),
            });
        }

        Ok(docs)
    }

    async fn generate_adrs(&self, snapshot: &CodebaseSnapshot) -> Result<Vec<Adr>> {
        let context = self.prepare_snapshot_context(snapshot);
        let prompt = prompts::adr_generation_prompt(&context);

        info!("Generating ADRs");

        let response = self
            .complete(&prompt, Some(prompts::SYSTEM_PROMPT))
            .await?;

        // Parse ADRs from response
        // For now, return a placeholder - real implementation would parse the markdown
        Ok(vec![Adr {
            id: "ADR-001".to_string(),
            title: "Architecture Inferred from Analysis".to_string(),
            context: "This ADR was auto-generated from codebase analysis.".to_string(),
            decision: response.content,
            alternatives: Vec::new(),
            consequences: Vec::new(),
            status: "proposed".to_string(),
        }])
    }

    async fn answer_question(
        &self,
        snapshot: &CodebaseSnapshot,
        question: &str,
    ) -> Result<AnswerWithRefs> {
        let context = self.prepare_snapshot_context(snapshot);
        let prompt = prompts::question_answer_prompt(&context, question);

        info!(question = %question, "Answering question");

        let response = self
            .complete(&prompt, Some(prompts::SYSTEM_PROMPT))
            .await?;

        Ok(AnswerWithRefs {
            answer: response.content,
            file_refs: Vec::new(), // TODO: Extract file references from response
            confidence: 0.8,
        })
    }

    async fn complete(&self, prompt: &str, system_prompt: Option<&str>) -> Result<LLMResponse> {
        let mut messages = Vec::new();

        if let Some(system) = system_prompt {
            messages.push(ChatMessage {
                role: "system".to_string(),
                content: system.to_string(),
            });
        }

        messages.push(ChatMessage {
            role: "user".to_string(),
            content: prompt.to_string(),
        });

        self.chat_completion(messages).await
    }

    async fn complete_stream(
        &self,
        prompt: &str,
        system_prompt: Option<&str>,
        callback: Box<dyn Fn(String) + Send>,
    ) -> Result<LLMResponse> {
        // TODO: Implement streaming
        // For now, just call the non-streaming version
        let response = self.complete(prompt, system_prompt).await?;
        callback(response.content.clone());
        Ok(LLMResponse {
            streamed: true,
            ..response
        })
    }
}

// OpenAI-compatible API types

#[derive(Debug, Serialize)]
struct ChatCompletionRequest {
    model: String,
    messages: Vec<ChatMessage>,
    max_tokens: usize,
    temperature: f32,
    stream: bool,
}

#[derive(Debug, Serialize, Deserialize)]
struct ChatMessage {
    role: String,
    content: String,
}

#[derive(Debug, Deserialize)]
struct ChatCompletionResponse {
    model: String,
    choices: Vec<Choice>,
    usage: Option<Usage>,
}

#[derive(Debug, Deserialize)]
struct Choice {
    message: ChatMessage,
    finish_reason: Option<String>,
}

#[derive(Debug, Deserialize)]
struct Usage {
    prompt_tokens: usize,
    completion_tokens: usize,
}

/// Mock LLM client for testing.
pub struct MockLlmClient {
    responses: std::collections::HashMap<String, String>,
}

impl MockLlmClient {
    /// Create a new mock client.
    pub fn new() -> Self {
        Self {
            responses: std::collections::HashMap::new(),
        }
    }

    /// Add a canned response for a pattern.
    pub fn add_response(&mut self, pattern: &str, response: &str) {
        self.responses.insert(pattern.to_string(), response.to_string());
    }
}

impl Default for MockLlmClient {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl LLMClient for MockLlmClient {
    async fn generate_architecture_overview(
        &self,
        _snapshot: &CodebaseSnapshot,
    ) -> Result<ArchitectureOverview> {
        Ok(ArchitectureOverview {
            content: "# Architecture Overview\n\nThis is a mock response.".to_string(),
            patterns: vec!["Layered".to_string()],
            components: vec![],
        })
    }

    async fn generate_component_docs(
        &self,
        _snapshot: &CodebaseSnapshot,
    ) -> Result<Vec<ComponentSummary>> {
        Ok(vec![])
    }

    async fn generate_adrs(&self, _snapshot: &CodebaseSnapshot) -> Result<Vec<Adr>> {
        Ok(vec![])
    }

    async fn answer_question(
        &self,
        _snapshot: &CodebaseSnapshot,
        question: &str,
    ) -> Result<AnswerWithRefs> {
        Ok(AnswerWithRefs {
            answer: format!("Mock answer to: {}", question),
            file_refs: vec![],
            confidence: 1.0,
        })
    }

    async fn complete(&self, prompt: &str, _system_prompt: Option<&str>) -> Result<LLMResponse> {
        // Check for matching patterns
        for (pattern, response) in &self.responses {
            if prompt.contains(pattern) {
                return Ok(LLMResponse {
                    content: response.clone(),
                    prompt_tokens: Some(100),
                    completion_tokens: Some(50),
                    model: "mock".to_string(),
                    streamed: false,
                    finish_reason: Some("stop".to_string()),
                });
            }
        }

        Ok(LLMResponse {
            content: "Mock response".to_string(),
            prompt_tokens: Some(10),
            completion_tokens: Some(5),
            model: "mock".to_string(),
            streamed: false,
            finish_reason: Some("stop".to_string()),
        })
    }

    async fn complete_stream(
        &self,
        prompt: &str,
        system_prompt: Option<&str>,
        callback: Box<dyn Fn(String) + Send>,
    ) -> Result<LLMResponse> {
        let response = self.complete(prompt, system_prompt).await?;
        callback(response.content.clone());
        Ok(response)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mock_client() {
        let client = MockLlmClient::new();

        let response = client.complete("Hello", None).await.unwrap();
        assert_eq!(response.content, "Mock response");
        assert_eq!(response.model, "mock");
    }

    #[tokio::test]
    async fn test_mock_client_with_pattern() {
        let mut client = MockLlmClient::new();
        client.add_response("test", "Test response!");

        let response = client.complete("This is a test", None).await.unwrap();
        assert_eq!(response.content, "Test response!");
    }
}
